apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: freelance-hub
  labels:
    app: backend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: localhost:5000/freelance-backend:24004405783
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: PORT
          value: "5000" 
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: backend-secrets-k8s
              key: MONGODB_URI
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets-k8s
              key: MONGODB_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets-k8s
              key: JWT_SECRET
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              name: backend-secrets-k8s
              key: RAZORPAY_KEY_ID
        - name: RAZORPAY_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets-k8s
              key: RAZORPAY_KEY_SECRET
        - name: OTEL_LOG_LEVEL
          value: "debug"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: freelance-hub
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: freelance-hub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
