apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: freelance-hub
data:
  REDIS_URI: "redis://redis-service.freelance-hub.svc.cluster.local:6379"
  JWT_EXPIRES_IN: "1d"
  NODE_ENV: "production"
  FRONTEND_URL: "http://freelance.local"
